version: 2

updates:
  - package-ecosystem: "uv"
    directory: "/"
    labels: [dependencies, python]
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      python-dependencies:
        patterns: ["**"]


  - package-ecosystem: "github-actions"
    directory: "/"
    labels: [dependency, github-actions]
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      github-actions:
        patterns: ["**"]
