[project]
name = "gha-toolkit"
version = "0.1.0"
description = "A python implementation of the github actions toolkit core package."
readme = "README.md"
authors = [
    { name = "rhawk117", email = "noplaceLike127dot0dot0dot1@proton.me" },
]
requires-python = ">=3.11,<3.15"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Typing :: Typed",
]
license = "Apache-2.0"
license-files = ["LICENSE"]
dependencies = []

[project.urls]
Homepage = "https://github.com/rhawk117/python-gha-toolkit"
Repository = "https://github.com/rhawk117/python-gha-toolkit"
Issues = "https://github.com/rhawk117/python-gha-toolkit/issues"
Changelog = "https://github.com/rhawk117/python-gha-toolkit/releases"


[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
check = [
    "mdformat>=1.0.0",
    "mdformat-gfm>=1.0.0",
    "mdformat-mkdocs>=5.3.0",
    "pre-commit>=4.6.2",
    "ruff>=0.16.5",
    "shellcheck-py>=0.11.0.1",
    "shfmt-py>=4.1.0",
    "ty>=0.0.75",
]
test = [
    "hypothesis>=6.165.10",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-mock>=3.15.1",
    "pytest-randomly>=4.1.0",
    "pytest-xdist>=3.8.0",
]
dev = [{ include-group = "check" }, { include-group = "test" }]
