required-version = ">=0.16.0"
target-version = "py311"
preview = false
respect-gitignore = true
src = ["src", "tests"]

[lint]
extend-select = [
    "ANN",
    "ARG",
    "ASYNC",
    "B",
    "FBT",
    "LOG",
    "PTH",
    "PT",
    "RET",
    "S",
    "SLF",
    "T20",
    "TID",
]

ignore = ["FBT003", "S101"]
explicit-preview-rules = true


[lint.per-file-ignores]
"tests/**" = ["S101"]

[format]
quote-style = "single"
docstring-code-format = true
