[environment]
python-version = "3.11"
python-platform = "all"
root = ["./src", "."]

[src]
include = ["src", "tests"]
respect-ignore-files = true
exclude-scripts = true

[analysis]
respect-type-ignore-comments = true
strict-equality-semantics = true
strict-generic-narrowing = true

[rules]
blanket-ignore-comment = "error"
division-by-zero = "error"
missing-type-argument = "error"
dynamic-function-decorator-return = "warn"
missing-override-decorator = "warn"
possibly-missing-attribute = "warn"
possibly-missing-import = "warn"
possibly-unresolved-reference = "warn"
unsound-assignment = "warn"
unsound-return-statement = "warn"
unsound-yield = "warn"
unsupported-dynamic-base = "warn"

[terminal]
error-on-warning = true
output-format = "full"